In [ ]:
'''
157] Implement program using numpy array to add two arrays.
'''
import numpy as np
s1=np.array([1,2,3,4,5,])
s2=np.array([6,7,8,9,10])
print(s1+s2)

In [ ]:
'''
158] Implement program for scalar operation using numpy array
'''
import numpy as np
s1=np.array([25,26,27,28])

print(s1+100)
print(s1-10)
print(s1*20)
print(s1/2)
print(s1//4)


In [ ]:
'''
159] Implement program to execute any 4 universal array function'''
import numpy as np
p1=np.array([1,2,3,4,5])
p2=np.array([6,7,8,9,10])
p3=np.array([1,4,9,16,25])


print(np.add(p1,p2))
print("min",np.min(p1))
print("max",np.max(p1))
print("mean",np.mean(p1))
print("Square :",np.sqrt(p3))
print("Square:",np.square(p1))

In [3]:
'''
160] Implement program to to display multi-dimensional array using following function
 1.save  2.load     3.save      4.loadtxt
'''
import numpy as np
s1=np.array([[25,7,2006],[28,11,2005]])

np.save("numpy_op.npy",s1)              #using save function
print(np.load("numpy_op.npy") )                #using load function


np.savetxt("numpy_op.txt",s1)
print(np.loadtxt("numpy_op.txt"))


[[  25    7 2006]
 [  28   11 2005]]
[[  25.    7. 2006.]
 [  28.   11. 2005.]]
